import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;

/**
 * The `ChatGPT` class provides a method for interacting with the OpenAI ChatGPT API
 * @author Victor Partain
 * @see https://stackoverflow.com/questions/tagged/chatgpt-api
 * @see https://github.com/openai/chatbot-api-java
 * @project Nyx
 */
public class Chatgpt implements Serializable {
    private static final long serialVersionUID = 1L;
    DoublyLinkedList<String> responseHistory = new DoublyLinkedList<>();

    /**
     * Generates a response from the ChatGPT API based on the provided message.
     *
     * @param message The input message from the user.
     * @return The response generated by the ChatGPT API.
     */
    public String getResponse(String message) {
        String url = "https://api.openai.com/v1/chat/completions";
        String apiKey;// API key for accessing the ChatGPT API.
        String model = "gpt-3.5-turbo"; // The version of the ChatGPT model to use for generating responses.

        try {
            // Create the HTTP POST request
            URL obj = new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();
            con.setRequestMethod("POST");
            con.setRequestProperty("Authorization", "Bearer " + apiKey);
            con.setRequestProperty("Content-Type", "application/json");

            // Build the request body
            String body = "{\"model\": \"" + model + "\", \"messages\": [{\"role\": \"user\", \"content\": \"" + message + "\"}]}";
            con.setDoOutput(true);
            OutputStreamWriter writer = new OutputStreamWriter(con.getOutputStream());
            writer.write(body);
            writer.flush();
            writer.close();

            // Get the response
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();
            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            // Extract and return the response
            String extractedResponse = extractContentFromResponse(response.toString());
            
            // Store the response in the doubly linked list
            responseHistory.addLast(extractedResponse);
            
            return extractedResponse;

        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Extracts the response content from the JSON response received from the ChatGPT API.
     *
     * @param response The JSON response from the ChatGPT API.
     * @return The content of the response generated by ChatGPT.
     */
    private String extractContentFromResponse(String response) {
        int startMarker = response.indexOf("content") + 11; // Marker for where the content starts.
        int endMarker = response.indexOf("\"", startMarker); // Marker for where the content ends.
        return response.substring(startMarker, endMarker); // Returns the substring containing only the response.
    }

    /**
     * Returns a string representation of the response history.
     *
     * @return a string representation of the response history
     */
    public String getResponseHistory() {
        return responseHistory.toString();
    }

}